name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Maven
      run: |
        mvn clean package
        mvn deploy -Dregistry=https://maven.pkg.github.com/dacasals -Dtoken=${{ secrets.GH_TOKEN }}


    - uses: actions/upload-artifact@v1
      with:
        name: sparql-query2vec.jar
        path: target/graph-edit-distance-1.0-SNAPSHOT.jar